name: LanguageReader
options:
  bundleIdPrefix: com.local
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0

targets:
  LanguageReader:
    type: application
    platform: iOS
    sources: [LanguageReader]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.local.LanguageReader
        INFOPLIST_KEY_CFBundleDisplayName: LanguageReader
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    dependencies:
      - sdk: libsqlite3.tbd

  LanguageReaderTests:
    type: bundle.unit-test
    platform: iOS
    sources: [LanguageReaderTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.local.LanguageReaderTests
    dependencies:
      - target: LanguageReader
